DryChem: common-utilities/libs/math/tests/testCalculus/testDifferentiationMethods.hpp File Reference
testDifferentiationMethods.hpp File Reference
#include <cstddef>
#include <sstream>
#include <vector>
#include <common-utils/math.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testDifferentiationMethods, forwardDifferenceMethodReturnsAVectorWithASizeOneLessThanTheInputs)
GTEST_TEST (testDifferentiationMethods, backwardsDifferenceMethodReturnsAVectorWithASizeOneLessThanTheInputs)
GTEST_TEST (testDifferentiationMethods, defaultCenteredDifferenceMethodReturnsAVectorWithASizeEqualToThatOfTheInputs)
GTEST_TEST (testDifferentiationMethods, nonDefaultCenteredDifferenceMethodReturnsAVectorWithASizeTwoLessThanTheInputs)
GTEST_TEST (testDifferentiationMethods, passingTwoDifferentlySizedContainersResultsInFatalException)
Function Documentation
GTEST_TEST() [1/5]
GTEST_TEST (testDifferentiationMethods , forwardDifferenceMethodReturnsAVectorWithASizeOneLessThanTheInputs)
References CppUtils::Math::forwardDifferenceMethod(), validate::x, and validate::y.
GTEST_TEST() [2/5]
GTEST_TEST (testDifferentiationMethods , backwardsDifferenceMethodReturnsAVectorWithASizeOneLessThanTheInputs)
References CppUtils::Math::backwardsDifferenceMethod(), validate::x, and validate::y.
GTEST_TEST() [3/5]
GTEST_TEST (testDifferentiationMethods , defaultCenteredDifferenceMethodReturnsAVectorWithASizeEqualToThatOfTheInputs)
References CppUtils::Math::centeredDifferenceMethod(), validate::x, and validate::y.
GTEST_TEST() [4/5]
GTEST_TEST (testDifferentiationMethods , nonDefaultCenteredDifferenceMethodReturnsAVectorWithASizeTwoLessThanTheInputs)
References CppUtils::Math::centeredDifferenceMethod(), validate::x, and validate::y.
GTEST_TEST() [5/5]
GTEST_TEST (testDifferentiationMethods , passingTwoDifferentlySizedContainersResultsInFatalException)
References CppUtils::Math::backwardsDifferenceMethod(), CppUtils::Math::centeredDifferenceMethod(), CppUtils::Math::forwardDifferenceMethod(), validate::x, and validate::y.