DryChem: common-utilities/libs/strings/samples/ciTokenizerExample.cpp File Reference
ciTokenizerExample.cpp File Reference
#include <cstddef>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <common-utils/strings.hpp>
Functions
std::map< DryChem::ci_string, std::size_t > ci_sort (const std::vector< std::string > &words, std::size_t &lengthLongestWord)
void printWords (const std::map< DryChem::ci_string, std::size_t > &ci_words, std::size_t lengthLongestWord)
int main ()
Function Documentation
ci_sort()
std::map< DryChem::ci_string, std::size_t > ci_sort (const std::vector< std::string > & words, std::size_t & lengthLongestWord)
Referenced by main().
printWords()
void printWords (const std::map< DryChem::ci_string, std::size_t > & ci_words, std::size_t lengthLongestWord)
Referenced by main().
main()
int main ()
References ci_sort(), and printWords().