DryChem: GetOpts::CommandLineParser< TArgs > Class Template Reference
GetOpts::CommandLineParser< TArgs > Class Template Reference
#include <commandLineParser.hpp>
Public Member Functions
CommandLineParser (const TArgs &... Options)
void setCommandLineOptions (int, const char **argv)
void printHelpMessage (const std::string &exampleUsage) const
Private Member Functions
std::string generateUsage () const
Private Attributes
fs::path programName
std::tuple< TArgs... > options
Constructor & Destructor Documentation
CommandLineParser()
template<typename... TArgs> GetOpts::CommandLineParser< TArgs >::CommandLineParser (const TArgs &... Options) inline
Member Function Documentation
generateUsage()
template<typename... TArgs> std::string GetOpts::CommandLineParser< TArgs >::generateUsage () const inline private
References GetOpts::CommandLineParser< TArgs >::options, and GetOpts::CommandLineParser< TArgs >::programName.
Referenced by GetOpts::CommandLineParser< TArgs >::printHelpMessage().
setCommandLineOptions()
template<typename... TArgs> void GetOpts::CommandLineParser< TArgs >::setCommandLineOptions (int , const char ** argv) inline
References GetOpts::CommandLineParser< TArgs >::programName.
Referenced by main().
printHelpMessage()
template<typename... TArgs> void GetOpts::CommandLineParser< TArgs >::printHelpMessage (const std::string & exampleUsage) const inline
References GetOpts::CommandLineParser< TArgs >::generateUsage(), GetOpts::CommandLineParser< TArgs >::options, and GetOpts::CommandLineParser< TArgs >::programName.
Member Data Documentation
programName
template<typename... TArgs> fs::path GetOpts::CommandLineParser< TArgs >::programName private
Referenced by GetOpts::CommandLineParser< TArgs >::generateUsage(), GetOpts::CommandLineParser< TArgs >::printHelpMessage(), and GetOpts::CommandLineParser< TArgs >::setCommandLineOptions().
options
template<typename... TArgs> std::tuple<TArgs...> GetOpts::CommandLineParser< TArgs >::options private
Referenced by GetOpts::CommandLineParser< TArgs >::generateUsage(), and GetOpts::CommandLineParser< TArgs >::printHelpMessage().
The documentation for this class was generated from the following file:
common-utilities/libs/meta/samples/commandLineParser.hpp