DryChem: CppUnits::PhysicalQuantity< BaseDimensionality > Class Template Reference
CppUnits::PhysicalQuantity< BaseDimensionality > Class Template Reference
#include <physicalQuantity.hpp>
Public Types
using DimensionalityType = typename BaseDimensionality::Type
Public Member Functions
constexpr PhysicalQuantity () noexcept=default
constexpr PhysicalQuantity (long double Magnitude) noexcept
constexpr PhysicalQuantity (const std::string &Magnitude)
constexpr long double getMagnitude () const noexcept
constexpr void setMagnitude (long double Magnitude) noexcept
constexpr auto operator+= (const PhysicalQuantity< BaseDimensionality > &rhs) noexcept
constexpr auto operator+ (const PhysicalQuantity< BaseDimensionality > &rhs) const noexcept
constexpr auto operator-= (const PhysicalQuantity< BaseDimensionality > &rhs) noexcept
constexpr auto operator- (const PhysicalQuantity< BaseDimensionality > &rhs) const noexcept
constexpr auto operator- () noexcept
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>>
constexpr auto operator* (T rhs) const noexcept
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>>
constexpr auto operator*= (T rhs) noexcept
constexpr auto operator*= (const PhysicalQuantity< Dimensionality<> > &rhs) noexcept
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>>
constexpr auto operator/ (T rhs) const noexcept
template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>>
constexpr auto operator/= (T rhs) noexcept
constexpr auto operator/= (const PhysicalQuantity< Dimensionality<> > &rhs) noexcept
Private Attributes
long double magnitude {0.0l}
Friends
constexpr friend bool operator== (const PhysicalQuantity< BaseDimensionality > &lhs, const PhysicalQuantity< BaseDimensionality > &rhs) noexcept
constexpr friend bool operator< (const PhysicalQuantity< BaseDimensionality > &lhs, const PhysicalQuantity< BaseDimensionality > &rhs) noexcept
constexpr friend std::ostream & operator<< (std::ostream &stream, const PhysicalQuantity< BaseDimensionality > &rhs)
Member Typedef Documentation
DimensionalityType
template<typename BaseDimensionality > using CppUnits::PhysicalQuantity< BaseDimensionality >::DimensionalityType = typename BaseDimensionality::Type
Constructor & Destructor Documentation
PhysicalQuantity() [1/3]
template<typename BaseDimensionality > constexpr CppUnits::PhysicalQuantity< BaseDimensionality >::PhysicalQuantity () constexpr default noexcept
PhysicalQuantity() [2/3]
template<typename BaseDimensionality > constexpr CppUnits::PhysicalQuantity< BaseDimensionality >::PhysicalQuantity (long double Magnitude) inline explicit constexpr noexcept
PhysicalQuantity() [3/3]
template<typename BaseDimensionality > constexpr CppUnits::PhysicalQuantity< BaseDimensionality >::PhysicalQuantity (const std::string & Magnitude) inline explicit constexpr
Allow strings to be parsed as physical quantities if they can first be parsed as long doubles.
Exceptions
std::invalid_argument If we can't convert the string to a long double our constructor will throw
Member Function Documentation
getMagnitude()
template<typename BaseDimensionality > constexpr long double CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude () const inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
Referenced by GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), and GTEST_TEST().
setMagnitude()
template<typename BaseDimensionality > constexpr void CppUnits::PhysicalQuantity< BaseDimensionality >::setMagnitude (long double Magnitude) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
Referenced by GTEST_TEST().
operator+=()
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator+= (const PhysicalQuantity< BaseDimensionality > & rhs) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
operator+()
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator+ (const PhysicalQuantity< BaseDimensionality > & rhs) const inline constexpr noexcept
operator-=()
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator-= (const PhysicalQuantity< BaseDimensionality > & rhs) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
operator-() [1/2]
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator- (const PhysicalQuantity< BaseDimensionality > & rhs) const inline constexpr noexcept
operator-() [2/2]
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator- () inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
operator*()
template<typename BaseDimensionality > template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>> constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator* (T rhs) const inline constexpr noexcept
operator*=() [1/2]
template<typename BaseDimensionality > template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>> constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator*= (T rhs) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
operator*=() [2/2]
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator*= (const PhysicalQuantity< Dimensionality<> > & rhs) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
operator/()
template<typename BaseDimensionality > template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>> constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator/ (T rhs) const inline constexpr noexcept
operator/=() [1/2]
template<typename BaseDimensionality > template<typename T , typename = std::enable_if_t<std::is_arithmetic_v<T>>> constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator/= (T rhs) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
operator/=() [2/2]
template<typename BaseDimensionality > constexpr auto CppUnits::PhysicalQuantity< BaseDimensionality >::operator/= (const PhysicalQuantity< Dimensionality<> > & rhs) inline constexpr noexcept
References CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude.
Friends And Related Symbol Documentation
operator==
template<typename BaseDimensionality > constexpr friend bool operator== (const PhysicalQuantity< BaseDimensionality > & lhs, const PhysicalQuantity< BaseDimensionality > & rhs) friend
operator<
template<typename BaseDimensionality > constexpr friend bool operator< (const PhysicalQuantity< BaseDimensionality > & lhs, const PhysicalQuantity< BaseDimensionality > & rhs) friend
operator<<
template<typename BaseDimensionality > constexpr friend std::ostream & operator<< (std::ostream & stream, const PhysicalQuantity< BaseDimensionality > & rhs) friend
Member Data Documentation
magnitude
template<typename BaseDimensionality > long double CppUnits::PhysicalQuantity< BaseDimensionality >::magnitude {0.0l} private
Referenced by CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator*=(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator*=(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator+=(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator-(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator-=(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator/=(), CppUnits::PhysicalQuantity< BaseDimensionality >::operator/=(), and CppUnits::PhysicalQuantity< BaseDimensionality >::setMagnitude().
The documentation for this class was generated from the following file:
cpp-units/include/cpp-units/types/physicalQuantity.hpp