DryChem: common-utilities/libs/math/tests/testUtilities/testBasicMathFunctions.hpp File Reference
testBasicMathFunctions.hpp File Reference
#include <cstddef>
#include <string>
#include <vector>
#include <common-utils/math.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testBasicMathFunctions, isEvenReturnCorrectBooleansForIntegralTypes)
GTEST_TEST (testBasicMathFunctions, isOddReturnCorrectBooleansForIntegralTypes)
GTEST_TEST (testBasicMathFunctions, withinRangeFunctionalityWorksForIntegers)
GTEST_TEST (testBasicMathFunctions, withinRangeFunctionalityWorksForDoubles)
GTEST_TEST (testBasicMathFunctions, withinRangeFunctionalityWorksForStrings)
GTEST_TEST (testBasicMathFunctions, linearInterpolationOf_y_along_x_gives_x)
Function Documentation
GTEST_TEST() [1/6]
GTEST_TEST (testBasicMathFunctions , isEvenReturnCorrectBooleansForIntegralTypes)
References CppUtils::Math::isEven().
GTEST_TEST() [2/6]
GTEST_TEST (testBasicMathFunctions , isOddReturnCorrectBooleansForIntegralTypes)
References CppUtils::Math::isOdd().
GTEST_TEST() [3/6]
GTEST_TEST (testBasicMathFunctions , withinRangeFunctionalityWorksForIntegers)
References CppUtils::Math::withinRange().
GTEST_TEST() [4/6]
GTEST_TEST (testBasicMathFunctions , withinRangeFunctionalityWorksForDoubles)
References CppUtils::Math::withinRange().
GTEST_TEST() [5/6]
GTEST_TEST (testBasicMathFunctions , withinRangeFunctionalityWorksForStrings)
GTEST_TEST() [6/6]
GTEST_TEST (testBasicMathFunctions , linearInterpolationOf_y_along_x_gives_x)
References CppUtils::Math::linearlyInterpolate(), validate::x, and validate::y.