DryChem: cpp-units/tests/testMathFunctions/testBasicMathFunctions.hpp File Reference
testBasicMathFunctions.hpp File Reference
#include <cmath>
#include <common-utils/math.hpp>
#include <gtest/gtest.h>
#include "cpp-units/physicalQuantities.hpp"
Functions
GTEST_TEST (testBasicMathFunctions, absoluteValueReturnsPositiveValueOfPhysicalQuantity)
GTEST_TEST (testBasicMathFunctions, exponentialFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
GTEST_TEST (testBasicMathFunctions, powerFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
GTEST_TEST (testBasicMathFunctions, trigonometricFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
GTEST_TEST (testBasicMathFunctions, hyperbolicFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
Function Documentation
GTEST_TEST() [1/5]
GTEST_TEST (testBasicMathFunctions , absoluteValueReturnsPositiveValueOfPhysicalQuantity)
GTEST_TEST() [2/5]
GTEST_TEST (testBasicMathFunctions , exponentialFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude().
GTEST_TEST() [3/5]
GTEST_TEST (testBasicMathFunctions , powerFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
References CppUnits::Math::cbrt(), CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude(), CppUnits::Math::pow(), and CppUnits::Math::sqrt().
GTEST_TEST() [4/5]
GTEST_TEST (testBasicMathFunctions , trigonometricFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude(), and CppUnits::Constants::pi.
GTEST_TEST() [5/5]
GTEST_TEST (testBasicMathFunctions , hyperbolicFunctionOverloadsAreEquivalentToTheirCorrespondingCmathFunctions)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude(), and CppUnits::Constants::pi.