DryChem: common-utilities/libs/math/samples/finiteDifferencesExample.cpp File Reference
finiteDifferencesExample.cpp File Reference
#include <algorithm>
#include <cstddef>
#include <iostream>
#include <numeric>
#include <vector>
#include <common-utils/math.hpp>
Functions
std::vector< double > differentiateThenIntegrate (const std::vector< double > &x, const std::vector< double > &y)
std::vector< double > integrateThenDifferentiate (const std::vector< double > &x, const std::vector< double > &y)
void validate (const std::vector< double > &expected, const std::vector< double > &actual, double tolerance)
int main ()
Function Documentation
differentiateThenIntegrate()
std::vector< double > differentiateThenIntegrate (const std::vector< double > & x, const std::vector< double > & y)
Referenced by main().
integrateThenDifferentiate()
std::vector< double > integrateThenDifferentiate (const std::vector< double > & x, const std::vector< double > & y)
Referenced by main().
validate()
void validate (const std::vector< double > & expected, const std::vector< double > & actual, double tolerance)
main()
int main ()
References differentiateThenIntegrate(), and integrateThenDifferentiate().