DryChem: common-utilities/libs/files/samples/markupParsingExample.cpp File Reference
markupParsingExample.cpp File Reference
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <unordered_map>
#include <vector>
#include <common-utils/files.hpp>
Classes
class SimpleMarkupStrategy
Functions
void createOutputFile (const fs::path &fileName)
int main ()
Function Documentation
createOutputFile()
void createOutputFile (const fs::path & fileName)
Referenced by GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), GTEST_TEST(), and main().
main()
int main ()
References createOutputFile().