DryChem: CppUtils::Testing::details::testing Namespace Reference
CppUtils::Testing::details::testing Namespace Reference
Classes
class MyClass
struct SumSquares
Functions
unsigned long long sumSquares (unsigned long long iter)
void voidSumSquares (unsigned long long iter)
Function Documentation
sumSquares()
unsigned long long CppUtils::Testing::details::testing::sumSquares (unsigned long long iter)
Referenced by GTEST_TEST(), GTEST_TEST(), and GTEST_TEST().
voidSumSquares()
void CppUtils::Testing::details::testing::voidSumSquares (unsigned long long iter)
Referenced by GTEST_TEST().