DryChem: validate Namespace Reference
validate Namespace Reference
Variables
x = np.linspace(0, 10000.1, 100002)
tuple y = (4 * x**2) + (2 * x) - 7
derivative1st = np.gradient(y, x)
integral2nd = integrate.cumtrapz(derivative1st, x, initial=0.0)
integral1st = integrate.cumtrapz(y, x, initial=0.0)
derivative2nd = np.gradient(integral1st, x)
int counter1 = 0
int counter2 = 0
int tolerance = 2 * (x[1] - x[0])
Variable Documentation
x
validate.x = np.linspace(0, 10000.1, 100002)
Referenced by CppUtils::Math.calculateVariance(), and GTEST_TEST().
y
tuple validate.y = (4 * x**2) + (2 * x) - 7
Referenced by GTEST_TEST(), and CppUtils::Math.linearlyInterpolate().
derivative1st
validate.derivative1st = np.gradient(y, x)
integral2nd
validate.integral2nd = integrate.cumtrapz(derivative1st, x, initial=0.0)
integral1st
validate.integral1st = integrate.cumtrapz(y, x, initial=0.0)
derivative2nd
validate.derivative2nd = np.gradient(integral1st, x)
counter1
int validate.counter1 = 0
counter2
int validate.counter2 = 0
tolerance
int validate.tolerance = 2 * (x[1] - x[0])