var namespace_cpp_utils_1_1_traits =
[
    [ "is_allocator_aware_container", "struct_cpp_utils_1_1_traits_1_1is__allocator__aware__container.html", null ],
    [ "is_allocator_aware_container< T, std::void_t< typename T::allocator_type > >", "struct_cpp_utils_1_1_traits_1_1is__allocator__aware__container_3_01_t_00_01std_1_1void__t_3_01tyfc168f5aae0f6b21d48410af8d0c1c97.html", null ],
    [ "is_associative_container", "struct_cpp_utils_1_1_traits_1_1is__associative__container.html", null ],
    [ "is_associative_container< T, std::void_t< typename T::key_type, typename T::key_compare, typename T::value_compare, decltype(std::declval< T >().key_comp()), decltype(std::declval< T >().value_comp())> >", "struct_cpp_utils_1_1_traits_1_1is__associative__container_3_01_t_00_01std_1_1void__t_3_01typenam008735a0e70e63639f1deabdcad08b5c.html", null ],
    [ "is_container", "struct_cpp_utils_1_1_traits_1_1is__container.html", null ],
    [ "is_container< T, std::void_t< typename T::value_type, typename T::reference, typename T::const_reference, typename T::iterator, typename T::const_iterator, typename T::difference_type, typename T::size_type, decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(std::declval< T >().cbegin()), decltype(std::declval< T >().cend()), decltype(std::declval< T >().max_size()), decltype(std::declval< T >().empty())> >", "struct_cpp_utils_1_1_traits_1_1is__container_3_01_t_00_01std_1_1void__t_3_01typename_01_t_1_1val9c4f754bbcc78342645a19a2b896a7f6.html", null ],
    [ "is_container_adapter", "struct_cpp_utils_1_1_traits_1_1is__container__adapter.html", null ],
    [ "is_container_adapter< T, std::void_t< typename T::container_type, typename T::value_type, typename T::size_type, typename T::reference, typename T::const_reference, decltype(std::declval< T >().empty()), decltype(std::declval< T >().size())> >", "struct_cpp_utils_1_1_traits_1_1is__container__adapter_3_01_t_00_01std_1_1void__t_3_01typename_014ff0eace031100fb2e03ee2c8782ed9f.html", null ],
    [ "is_reversible_container", "struct_cpp_utils_1_1_traits_1_1is__reversible__container.html", null ],
    [ "is_reversible_container< T, std::void_t< typename T::reverse_iterator, typename T::const_reverse_iterator, decltype(std::declval< T >().rbegin()), decltype(std::declval< T >().rend()), decltype(std::declval< T >().crbegin()), decltype(std::declval< T >().crend())> >", "struct_cpp_utils_1_1_traits_1_1is__reversible__container_3_01_t_00_01std_1_1void__t_3_01typename0fb18c1f0027bce48774457cb36fc296.html", null ],
    [ "is_sequence_container", "struct_cpp_utils_1_1_traits_1_1is__sequence__container.html", null ],
    [ "is_unordered_associative_container", "struct_cpp_utils_1_1_traits_1_1is__unordered__associative__container.html", null ],
    [ "is_unordered_associative_container< T, std::void_t< typename T::key_type, typename T::value_type, typename T::hasher, typename T::key_equal, typename T::local_iterator, typename T::const_local_iterator > >", "struct_cpp_utils_1_1_traits_1_1is__unordered__associative__container_3_01_t_00_01std_1_1void__t_e5bcb4ff789d461bd08c9729ea244725.html", null ]
];