DryChem: CppUnits::Math Namespace Reference
CppUnits::Math Namespace Reference
Namespaces
details
Functions
template<int Power, int L, int M, int T, int I, int Th, int N, int J>
constexpr auto pow (const PhysicalQuantity< Dimensionality< L, M, T, I, Th, N, J >> &physicalQuantity) noexcept
template<int L, int M, int T, int I, int Th, int N, int J, typename = std::enable_if_t<(L % 2 == 0) && (M % 2 == 0) && (T % 2 == 0) && (I % 2 == 0) && (Th % 2 == 0) && (N % 2 == 0) && (J % 2 == 0)>>
constexpr auto sqrt (const PhysicalQuantity< Dimensionality< L, M, T, I, Th, N, J >> &physicalQuantity) noexcept
template<int L, int M, int T, int I, int Th, int N, int J, typename = std::enable_if_t<(L % 3 == 0) && (M % 3 == 0) && (T % 3 == 0) && (I % 3 == 0) && (Th % 3 == 0) && (N % 3 == 0) && (J % 3 == 0)>>
constexpr auto cbrt (const PhysicalQuantity< Dimensionality< L, M, T, I, Th, N, J >> &physicalQuantity) noexcept
Function Documentation
pow()
template<int Power, int L, int M, int T, int I, int Th, int N, int J> constexpr auto CppUnits::Math::pow (const PhysicalQuantity< Dimensionality< L, M, T, I, Th, N, J >> & physicalQuantity) constexpr noexcept
References CppUnits::Math::details::PowImpl< Power, L, M, T, I, Th, N, J >::result(), and CppUnits::Math::details::InversePowImpl< Power, L, M, T, I, Th, N, J >::result().
Referenced by CppUtils::Math::findAbsoluteError(), and GTEST_TEST().
sqrt()
template<int L, int M, int T, int I, int Th, int N, int J, typename = std::enable_if_t<(L % 2 == 0) && (M % 2 == 0) && (T % 2 == 0) && (I % 2 == 0) && (Th % 2 == 0) && (N % 2 == 0) && (J % 2 == 0)>> constexpr auto CppUnits::Math::sqrt (const PhysicalQuantity< Dimensionality< L, M, T, I, Th, N, J >> & physicalQuantity) constexpr noexcept
Referenced by GTEST_TEST().
cbrt()
template<int L, int M, int T, int I, int Th, int N, int J, typename = std::enable_if_t<(L % 3 == 0) && (M % 3 == 0) && (T % 3 == 0) && (I % 3 == 0) && (Th % 3 == 0) && (N % 3 == 0) && (J % 3 == 0)>> constexpr auto CppUnits::Math::cbrt (const PhysicalQuantity< Dimensionality< L, M, T, I, Th, N, J >> & physicalQuantity) constexpr noexcept
Referenced by GTEST_TEST().