DryChem: CppUtils::Errors Namespace Reference
CppUtils::Errors Namespace Reference
Classes
struct ErrorMessage
class FatalException
struct is_fatal
struct is_fatal< ErrorSeverity::Fatal >
Enumerations
enum ErrorSeverity { ErrorSeverity::Warning, ErrorSeverity::Fatal }
Functions
template<ErrorSeverity Severity = ErrorSeverity::Warning>
void printErrorMessage (const ErrorMessage &error)
Variables
template<ErrorSeverity Severity>
constexpr bool is_fatal_v = is_fatal<Severity>::value
Convenience variable template for ease-of-use.
auto printFatalErrorMessage = [](const ErrorMessage& error) { printErrorMessage<ErrorSeverity::Fatal>(error); }
A convenience function for printing an error message when said error is fatal.
Enumeration Type Documentation
ErrorSeverity
enum CppUtils::Errors::ErrorSeverity strong
A simple scoped enumeration for use in defining the severity of the error in a cleaner, more verbose way than simple boolean flags would allow.
Enumerator
Warning
Describes the severity of an error that only requires a warning.
Fatal
Describes the severity of a fatal, non-recoverable error.
Function Documentation
printErrorMessage()
template<ErrorSeverity Severity = ErrorSeverity::Warning> void CppUtils::Errors::printErrorMessage (const ErrorMessage & error) inline
A simple function to format and print an error message according to 1) the information provided, and 2) the severity of the given error.
Template Parameters
Severity The severity of the error in question (defaults to a warning message)
Parameters
error The error message and other information about the location of the error
References CppUtils::Errors::ErrorMessage::fileName, CppUtils::Errors::ErrorMessage::lineNumber, CppUtils::Errors::ErrorMessage::message, and CppUtils::Errors::ErrorMessage::programName.
Referenced by GTEST_TEST(), and CppUtils::Strings::lexical_cast().
Variable Documentation
is_fatal_v
template<ErrorSeverity Severity> constexpr bool CppUtils::Errors::is_fatal_v = is_fatal<Severity>::value constexpr
printFatalErrorMessage
auto CppUtils::Errors::printFatalErrorMessage = [](const ErrorMessage& error) { printErrorMessage<ErrorSeverity::Fatal>(error); } inline
Referenced by GTEST_TEST(), and CppUtils::Errors::FatalException::handleErrorWithMessage().