DryChem: common-utilities/libs/math/tests/testStatistics/testLinearLeastSquaresFitting.hpp File Reference
testLinearLeastSquaresFitting.hpp File Reference
#include <cmath>
#include <vector>
#include <common-utils/math.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testLinearLeastSquaresFitting, linearLeastSquaresFittingReturnsMultipleValuesInAStruct)
GTEST_TEST (testLinearLeastSquaresFitting, linearLeastSquaresFittingCanReturnATypeCompatibleWithStructuredBinding)
GTEST_TEST (testLinearLeastSquaresFitting, passingTwoDifferentlySizedContainersResultsInFatalException)
Function Documentation
GTEST_TEST() [1/3]
GTEST_TEST (testLinearLeastSquaresFitting , linearLeastSquaresFittingReturnsMultipleValuesInAStruct)
References CppUtils::Math::findAbsoluteError(), CppUtils::Math::details::LinearLeastSquaresResult< T_slope, T_intercept, T_variance, typename >::intercept, CppUtils::Math::linearLeastSquaresFitting(), CppUtils::Math::details::LinearLeastSquaresResult< T_slope, T_intercept, T_variance, typename >::slope, CppUnits::Math::sqrt(), CppUtils::Math::details::LinearLeastSquaresResult< T_slope, T_intercept, T_variance, typename >::variance, validate::x, and validate::y.
GTEST_TEST() [2/3]
GTEST_TEST (testLinearLeastSquaresFitting , linearLeastSquaresFittingCanReturnATypeCompatibleWithStructuredBinding)
References CppUtils::Math::findAbsoluteError(), CppUtils::Math::linearLeastSquaresFitting(), CppUnits::Math::sqrt(), validate::x, and validate::y.
GTEST_TEST() [3/3]
GTEST_TEST (testLinearLeastSquaresFitting , passingTwoDifferentlySizedContainersResultsInFatalException)
References CppUtils::Math::linearLeastSquaresFitting(), validate::x, and validate::y.