DryChem: cpp-units/libs/math/tests/testMathFunctions/testAdvancedMathFunctions.hpp File Reference
testAdvancedMathFunctions.hpp File Reference
#include <array>
#include <vector>
#include <common-utils/math.hpp>
#include <gtest/gtest.h>
#include "cpp-units/physicalQuantities.hpp"
Functions
GTEST_TEST (testBasicMathFunctions, weCanTakeTheAverageOfContainersOfPhysicalQuantities)
GTEST_TEST (testBasicMathFunctions, weCanTakeTheVarianceOfContainersOfPhysicalQuantities)
GTEST_TEST (testBasicMathFunctions, weCanFitALineThroughAContainerOfPhysicalQuantities)
GTEST_TEST (testBasicMathFunctions, weCanApproximateTheDerivativeOfAContainerOfPhysicalQuantities)
GTEST_TEST (testBasicMathFunctions, weCanApproximateTheIntegralOfAContainerOfPhysicalQuantities)
Function Documentation
GTEST_TEST() [1/5]
GTEST_TEST (testBasicMathFunctions , weCanTakeTheAverageOfContainersOfPhysicalQuantities)
References CppUtils::Math::calculateAverage(), validate::x, and validate::y.
GTEST_TEST() [2/5]
GTEST_TEST (testBasicMathFunctions , weCanTakeTheVarianceOfContainersOfPhysicalQuantities)
References CppUtils::Math::calculateVariance(), CppUtils::Math::findAbsoluteError(), CppUnits::Math::sqrt(), validate::x, and validate::y.
GTEST_TEST() [3/5]
GTEST_TEST (testBasicMathFunctions , weCanFitALineThroughAContainerOfPhysicalQuantities)
References CppUtils::Math::findAbsoluteError(), CppUtils::Math::linearLeastSquaresFitting(), CppUnits::Math::sqrt(), validate::x, and validate::y.
GTEST_TEST() [4/5]
GTEST_TEST (testBasicMathFunctions , weCanApproximateTheDerivativeOfAContainerOfPhysicalQuantities)
References CppUtils::Math::centeredDifferenceMethod().
GTEST_TEST() [5/5]
GTEST_TEST (testBasicMathFunctions , weCanApproximateTheIntegralOfAContainerOfPhysicalQuantities)
References CppUtils::Math::cumulativeTrapzIntegration().