DryChem: common-utilities/libs/utilities/tests/testTesting/testPerformanceTesting.hpp File Reference
testPerformanceTesting.hpp File Reference
#include <cstddef>
#include <common-utils/utilities.hpp>
#include <gtest/gtest.h>
#include "../details/testingDetails.hpp"
Functions
GTEST_TEST (testPerformanceTesting, timeAndInvokeReturnsAReturnTypeStruct)
GTEST_TEST (testPerformanceTesting, timeAndInvokeWithAVoidFunctionReturnsOnlyTheTime)
GTEST_TEST (testPerformanceTesting, timeAndInvokeWithAFunctorReturnsResultAndTime)
GTEST_TEST (testPerformanceTesting, timeAndInvokeWithAMemberFunctionReturnsResultAndTime)
GTEST_TEST (testPerformanceTesting, timeAndInvokeWithAPlainFunctionReturnsResultAndTime)
GTEST_TEST (testPerformanceTesting, timeAndInvokeWithALambdaFunctionReturnsResultAndTime)
Function Documentation
GTEST_TEST() [1/6]
GTEST_TEST (testPerformanceTesting , timeAndInvokeReturnsAReturnTypeStruct)
References CppUtils::Testing::details::ReturnType< F, TArgs >::result, CppUtils::Testing::details::testing::sumSquares(), and CppUtils::Testing::details::ReturnType< F, TArgs >::time.
GTEST_TEST() [2/6]
GTEST_TEST (testPerformanceTesting , timeAndInvokeWithAVoidFunctionReturnsOnlyTheTime)
References CppUtils::Testing::details::testing::voidSumSquares().
GTEST_TEST() [3/6]
GTEST_TEST (testPerformanceTesting , timeAndInvokeWithAFunctorReturnsResultAndTime)
GTEST_TEST() [4/6]
GTEST_TEST (testPerformanceTesting , timeAndInvokeWithAMemberFunctionReturnsResultAndTime)
GTEST_TEST() [5/6]
GTEST_TEST (testPerformanceTesting , timeAndInvokeWithAPlainFunctionReturnsResultAndTime)
References CppUtils::Testing::details::testing::sumSquares().
GTEST_TEST() [6/6]
GTEST_TEST (testPerformanceTesting , timeAndInvokeWithALambdaFunctionReturnsResultAndTime)
References CppUtils::Testing::details::testing::sumSquares().