DryChem: common-utilities/libs/strings/tests/testUtilities/testTokenizer.hpp File Reference
testTokenizer.hpp File Reference
#include <deque>
#include <forward_list>
#include <list>
#include <map>
#include <set>
#include <string>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <common-utils/strings.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testTokenizer, has_mapped_typeReturnsTrueForStdMapsAndOtherMapContainersOnly)
GTEST_TEST (testTokenizer, memberTypesForATokenizerAreCorrect)
GTEST_TEST (testTokenizer, ctadWorksForTheStringConstructorOfAStdStringTokenizer)
GTEST_TEST (testTokenizer, ctadWorksForTheStringConstructorOfACaseInsensitiveTokenizer)
GTEST_TEST (testTokenizer, withoutATemplateParameterSplitReturnsAVectorOfStrings)
GTEST_TEST (testTokenizer, aDequeOfStringsSplitsTokensNormally)
GTEST_TEST (testTokenizer, aForwardListOfStringsReversesTheTokens)
GTEST_TEST (testTokenizer, aListOfStringsSplitsTokensNormally)
GTEST_TEST (testTokenizer, aMultiSetOfStringsOrdersTokens)
GTEST_TEST (testTokenizer, aSetOfStringsOrdersTokens)
GTEST_TEST (testTokenizer, aSetOfCaseInsensitiveStringsOrdersTokensWithoutRegardToCase)
GTEST_TEST (testTokenizer, aStringTruncatesAllButTheFirstLetterOfTheToken)
GTEST_TEST (testTokenizer, anUnorderedMultiSetHashesTheTokens)
GTEST_TEST (testTokenizer, anUnorderedSetHashesTheTokens)
GTEST_TEST (testTokenizer, weCanCastStringsToAnyTypeJustBySpecifyingTheContainersTemplateParameter)
Function Documentation
GTEST_TEST() [1/15]
GTEST_TEST (testTokenizer , has_mapped_typeReturnsTrueForStdMapsAndOtherMapContainersOnly)
GTEST_TEST() [2/15]
GTEST_TEST (testTokenizer , memberTypesForATokenizerAreCorrect)
GTEST_TEST() [3/15]
GTEST_TEST (testTokenizer , ctadWorksForTheStringConstructorOfAStdStringTokenizer)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [4/15]
GTEST_TEST (testTokenizer , ctadWorksForTheStringConstructorOfACaseInsensitiveTokenizer)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [5/15]
GTEST_TEST (testTokenizer , withoutATemplateParameterSplitReturnsAVectorOfStrings)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [6/15]
GTEST_TEST (testTokenizer , aDequeOfStringsSplitsTokensNormally)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [7/15]
GTEST_TEST (testTokenizer , aForwardListOfStringsReversesTheTokens)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [8/15]
GTEST_TEST (testTokenizer , aListOfStringsSplitsTokensNormally)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [9/15]
GTEST_TEST (testTokenizer , aMultiSetOfStringsOrdersTokens)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [10/15]
GTEST_TEST (testTokenizer , aSetOfStringsOrdersTokens)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [11/15]
GTEST_TEST (testTokenizer , aSetOfCaseInsensitiveStringsOrdersTokensWithoutRegardToCase)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [12/15]
GTEST_TEST (testTokenizer , aStringTruncatesAllButTheFirstLetterOfTheToken)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [13/15]
GTEST_TEST (testTokenizer , anUnorderedMultiSetHashesTheTokens)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [14/15]
GTEST_TEST (testTokenizer , anUnorderedSetHashesTheTokens)
References CppUtils::Strings::Tokenizer().
GTEST_TEST() [15/15]
GTEST_TEST (testTokenizer , weCanCastStringsToAnyTypeJustBySpecifyingTheContainersTemplateParameter)
References CppUtils::Strings::Tokenizer().