DryChem: common-utilities/libs/math/tests/testStatistics/testStatisticalFunctions.hpp File Reference
testStatisticalFunctions.hpp File Reference
#include <array>
#include <cmath>
#include <vector>
#include <common-utils/math.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testStatisticalFunctions, orderOfMagnitudeIsCalculatedCorrectly)
GTEST_TEST (testStatisticalFunctions, weCanEasilyApproximatePiToACetainDegreeOfAccurracy)
GTEST_TEST (testStatisticalFunctions, averageCalculationsWorkOnARangeOfValuesInAGivenContainer)
GTEST_TEST (testStatisticalFunctions, varianceCalculationsWorkOnARangeOfValuesInAGivenContainer)
Function Documentation
GTEST_TEST() [1/4]
GTEST_TEST (testStatisticalFunctions , orderOfMagnitudeIsCalculatedCorrectly)
References CppUtils::Math::findOrderOfMagnitude().
GTEST_TEST() [2/4]
GTEST_TEST (testStatisticalFunctions , weCanEasilyApproximatePiToACetainDegreeOfAccurracy)
References CppUtils::Math::findAbsoluteError().
GTEST_TEST() [3/4]
GTEST_TEST (testStatisticalFunctions , averageCalculationsWorkOnARangeOfValuesInAGivenContainer)
References CppUtils::Math::calculateAverage(), validate::x, and validate::y.
GTEST_TEST() [4/4]
GTEST_TEST (testStatisticalFunctions , varianceCalculationsWorkOnARangeOfValuesInAGivenContainer)
References CppUtils::Math::calculateVariance(), CppUtils::Math::findAbsoluteError(), CppUnits::Math::sqrt(), validate::x, and validate::y.