DryChem: cpp-units/libs/physicalQuantities/tests/testOperators/testArithmeticOperators.hpp File Reference
testArithmeticOperators.hpp File Reference
#include <gtest/gtest.h>
#include "cpp-units/physicalQuantities.hpp"
Functions
GTEST_TEST (testArithmeticOperators, overloadedAdditionOperatorsActOnlyOnPhysicalQuantities)
GTEST_TEST (testArithmeticOperators, overloadedSubtractionOperatorsActOnlyOnPhysicalQuantities)
GTEST_TEST (testArithmeticOperators, unaryMinusOperatorNegatesMagnitude)
GTEST_TEST (testArithmeticOperators, overloadedMultiplicationOperatorsActOnPhysicalQuantitiesAndNumericTypes)
GTEST_TEST (testArithmeticOperators, overloadedDivisionOperatorsActOnPhysicalQuantitiesAndNumericTypes)
Function Documentation
GTEST_TEST() [1/5]
GTEST_TEST (testArithmeticOperators , overloadedAdditionOperatorsActOnlyOnPhysicalQuantities)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude().
GTEST_TEST() [2/5]
GTEST_TEST (testArithmeticOperators , overloadedSubtractionOperatorsActOnlyOnPhysicalQuantities)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude().
GTEST_TEST() [3/5]
GTEST_TEST (testArithmeticOperators , unaryMinusOperatorNegatesMagnitude)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude().
GTEST_TEST() [4/5]
GTEST_TEST (testArithmeticOperators , overloadedMultiplicationOperatorsActOnPhysicalQuantitiesAndNumericTypes)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude().
GTEST_TEST() [5/5]
GTEST_TEST (testArithmeticOperators , overloadedDivisionOperatorsActOnPhysicalQuantitiesAndNumericTypes)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude().