DryChem: common-utilities/libs/strings/tests/testUtilities/testStringUtilities.hpp File Reference
testStringUtilities.hpp File Reference
#include <string>
#include <common-utils/strings.hpp>
#include <gtest/gtest.h>
Functions
GTEST_TEST (testStringUtilities, foundSubstrFunctionCanBeCalledWithStdStrings)
GTEST_TEST (testStringUtilities, foundSubstrFunctionCanBeCalledWithChars)
GTEST_TEST (testStringUtilities, foundSubstrFindsIndividualWordsInLongerString)
GTEST_TEST (testStringUtilities, foundSubstrFunctionCanBeCaseSensitive)
Function Documentation
GTEST_TEST() [1/4]
GTEST_TEST (testStringUtilities , foundSubstrFunctionCanBeCalledWithStdStrings)
References CppUtils::Strings::foundSubstr().
GTEST_TEST() [2/4]
GTEST_TEST (testStringUtilities , foundSubstrFunctionCanBeCalledWithChars)
References CppUtils::Strings::foundSubstr().
GTEST_TEST() [3/4]
GTEST_TEST (testStringUtilities , foundSubstrFindsIndividualWordsInLongerString)
References CppUtils::Strings::foundSubstr().
GTEST_TEST() [4/4]
GTEST_TEST (testStringUtilities , foundSubstrFunctionCanBeCaseSensitive)
References CppUtils::Strings::foundSubstr().