DryChem: cpp-units/libs/physicalQuantities/tests/testTypes/testPhysicalQuantity.hpp File Reference
testPhysicalQuantity.hpp File Reference
#include <exception>
#include <sstream>
#include <stdexcept>
#include <string>
#include <common-utils/errors.hpp>
#include <gtest/gtest.h>
#include "cpp-units/physicalQuantities.hpp"
Functions
GTEST_TEST (testPhysicalQuantity, aPhysicalQuantityKnowsItsDimensionality)
GTEST_TEST (testPhysicalQuantity, defaultInitializerSetsPhysicalQuantitysMagnitudeToZero)
GTEST_TEST (testPhysicalQuantity, setterFunctionsCanTakeDoubleValuesAsInputParameters)
GTEST_TEST (testPhysicalQuantity, physicalQuantitiesCanBeConstructedFromStrings)
GTEST_TEST (testPhysicalQuantity, stringConstructorCanThrowAnException)
Function Documentation
GTEST_TEST() [1/5]
GTEST_TEST (testPhysicalQuantity , aPhysicalQuantityKnowsItsDimensionality)
GTEST_TEST() [2/5]
GTEST_TEST (testPhysicalQuantity , defaultInitializerSetsPhysicalQuantitysMagnitudeToZero)
GTEST_TEST() [3/5]
GTEST_TEST (testPhysicalQuantity , setterFunctionsCanTakeDoubleValuesAsInputParameters)
References CppUnits::PhysicalQuantity< BaseDimensionality >::getMagnitude(), and CppUnits::PhysicalQuantity< BaseDimensionality >::setMagnitude().
GTEST_TEST() [4/5]
GTEST_TEST (testPhysicalQuantity , physicalQuantitiesCanBeConstructedFromStrings)
GTEST_TEST() [5/5]
GTEST_TEST (testPhysicalQuantity , stringConstructorCanThrowAnException)
References CppUtils::Errors::FatalException::handleErrorWithMessage(), CppUtils::Errors::ErrorMessage::message, and CppUtils::Errors::ErrorMessage::programName.