name: cmake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    # if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      working-directory: $GITHUB_WORKSPACE
      shell: pwsh
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Dchem_build_all=ON -Dutils_exclude_scripts=ON

    - name: Build
      working-directory: $GITHUB_WORKSPACE
      shell: pwsh
      run: cmake --build .

    - name: Test
      working-directory: $GITHUB_WORKSPACE
      shell: pwsh
      run: ctest --output-on-failure

    - name: Verify
      working-directory: $GITHUB_WORKSPACE
      shell: pwsh
      run: |
        $locationOfSamples = gci -Path . -Filter ciTokenizerExample.exe -Recurse -ErrorAction SilentlyContinue -Force
        cd $locationOfSamples.DirectoryName
        $files = gci *.exe
        foreach ($file in $files) { echo "Hello World!*" | cmd /c $file; if (-not $?) { echo "" } }

    