name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '21 16 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      shell: bash
      run: |
        sudo apt-get install lcov
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=DEBUG -Dchem_enable_coverage=ON
        cmake --build .
        sudo cmake --build . --target install
        ctest --output-on-failure
        lcov --directory . --capture --output-file coverage.info
        lcov --remove coverage.info '*gtest*' '*/libs/*' '/usr/*' --output-file coverage.info
    
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        file: coverage.info

    - name: CodeCov GitHub Action
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.info

