name: Linux

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    # if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
        
    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Dchem_build_all=ON

    - name: Build
      run: cmake --build .

    - name: Install
      run: sudo cmake --build . --target install

    - name: Test
      run: ctest --output-on-failure

    - name: Verify
      run: |
        cd bin/samples
        for file in *; do printf 'Hello, World!\n*' | ./$file || echo -n; done
